# Generated by Django 5.0.1 on 2025-06-06 23:21

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload a profile photo (optional)', null=True, upload_to=students.models.student_photo_path),
        ),
    ]
