# Generated by Django 5.0.1 on 2025-06-06 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademicinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info', to='students.student'),
        ),
    ]
