# Generated by Django 5.2.1 on 2025-05-22 01:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('instructors', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], max_length=1)),
                ('time_marked', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('minutes_late', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(180)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-date', 'course'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_337b1d_idx'), models.Index(fields=['student', 'date'], name='attendance__student_588cfe_idx')],
                'unique_together': {('student', 'course', 'date')},
            },
        ),
    ]
